### ISSUE TITLE
Using content types other than json could be easier.

### ISSUE THREAD

**Issue by bnppl** [zfcampus/zf-content-negotiation#26]
I am trying to add XML as an available content type for my api using this library, which I found quite easy to do for setting the response type by registering an XML ViewModel, Renderer and Strategy.

I was a bit disappointed with the support for retrieving request data. The ContentTypeListener is not very extensible and is [hardcoded to handle only form data and JSON.](https://github.com/zfcampus/zf-content-negotiation/blob/674b4175092d6411d0a2b9e950e38a7d4154a6f4/src/ContentTypeListener.php#L68-L75)

Would there be any interest in a pull request to make this more extensible? )

**Comment by weierophinney** [comment]
@bnppl With the event system in ZF2, you can register your own listeners for munging request data. If you register at the same or lower priority as the ContentTypeListener, your own code can overwrite the body params based on the results of your own deserialization. We chose this route, as deserialization will typically be one of JSON, form-encoded, or multipart-form — all of which we can easily handle — or something custom.

We could potentially add a plugin system to zf-content-negotiation, but considering the event system already exists, this seems like overkill.

**Comment by bnppl** [comment]
That's what I ended up doing, thanks!
