### ISSUE TITLE
Sloppy internal requests

### ISSUE THREAD

**Issue by im-bart** [zfcampus/zf-content-negotiation#28]
My case is as follows: I have an RPC request that is POSTed with some info, this will invoke the ZF\ContentNegotiation\ContentTypeListener and create a new ZFContentNegotiationParameterData in the event, which is picked up by REST controllers. Now, this request does an internal forward dispatch to a REST controller, which unfortunately does not trigger ContentTypeListener, so I have to invoke it myself before my altered request content is picked up:
```php
$this->getRequest()->setMethod('PATCH');
$this->getRequest()->setContent(json_encode($request));
$this->getRequest()->getHeaders()->addHeader(\Zend\Http\Header\ContentType::fromString('Content-Type: application/json'));
(new ContentTypeListener)->__invoke($this->getEvent());
$hal = $this->forward()->dispatch('Some\\Rest\\Controller');
```
This works, but maybe it can be attached to, say, the dispatch event without breaking things? Any thoughts?

**Comment by weierophinney** [comment]
Personally, I recommend never using the `forward()` plugin. Instead, invoke the objects that do the work directly. Write a service layer that has the various operations that you'll be invoking from your REST resource and/or RPC controllers, and have those consume it.
