### ISSUE TITLE
Unable to resolve Accept header to a representation

### ISSUE THREAD

**Issue by n3vrax** [zfcampus/zf-content-negotiation#33]
I'm having a problem with  an RPC service
using latest 1.1.0 release of apigilty

after creating an RPC service from UI, the content negotiation config looks like this

```php
'zf-content-negotiation' => array(
        'controllers' => array(
            'Name\\V1\\Rpc\\Search\\Controller' => array(
                'content_name' => 'Json',
                'selectors' => array(
                    'ZF\\ContentNegotiation\\JsonModel' => array(
                        0 => 'application/json',
                        1 => 'application/*+json',
                    ),
                ),
            ),
        ),
```

I do not include accept and content type whitelist as those look good and doesn't seem to be the culprit
if a make a valid post request to this RPC endpoint(accept header set to application/json, and a valid JSON POST body, I get 

406 Unable to resolve Accept header to a representation

my controller for test look like this

```php
<?php
namespace Name\V1\Rpc\Search;

use Zend\Mvc\Controller\AbstractActionController;
use ZF\ContentNegotiation\ViewModel;

class SearchController extends AbstractActionController
{
    public function searchAction()
    {
        return new ViewModel(array(
            'keyword' => 'test', 
        ));
    }
}
```

By playing around, I noticed that if I change the config section to this

```php
'zf-content-negotiation' => array(
        'controllers' => array(
            'Name\\V1\\Rpc\\Search\\Controller' => 'Json'
        ),
```

it doesn't give that error anymore and the valid response is returned
I'm wondering if this is a config structure issue, or I'm doing something wrong
I also have some REST endpoints in there, but without any problems

**Comment by weierophinney** [comment]
I cannot reproduce on a clean install of Apigility; creating an RPC service correctly creates the following content negotiation configuration:

```php
'zf-content-negotiation' => array(
    'controllers' => array(
        'Api\\V1\\Rpc\\Ping\\Controller' => 'Json',
    ),
    // default accept/content_type whitelists
)
```

I'm unsure where or how you received the configuration you did; to my knowledge, the admin code has never generated it. :-/
