### ISSUE TITLE
All whitespaces are stripped from payload

### ISSUE THREAD

**Issue by bramstroker** [zfcampus/zf-content-negotiation#38]
@weierophinney since your last commit all the whitespaces are stripped from the json payload, not only those at the end or beginning. Isn't a simple `trim()` sufficient?

    $json = preg_replace('/^\s*/m', '', $json);
    $json = preg_replace('/\s*/m', '', $json);

Should be:

    $json = preg_replace('/^\s*/m', '', $json);
    $json = preg_replace('/\s*$/m', '', $json);

**Comment by weierophinney** [comment]
Fixed with #39.
