### ISSUE TITLE
Question / issue: ContentNegotiationOptions and zf-oauth2

### ISSUE THREAD

**Issue by lolcode** [zfcampus/zf-content-negotiation#45]
Hi,

I think we have a versioning problem.

First, take a look at the zf-oauth2 module config (lines 106, 107 - https://github.com/zfcampus/zf-oauth2/blob/master/config/module.config.php)

```php
 'zf-content-negotiation' => array(
        'ZF\OAuth2\Controller\Auth' => array(
```
The introduction of ContentNegotiationOptions (commited july, 6) brokes this array key, throwing an Exception, since the option doesn't have a set method for "ZF\OAuth2\Controller\Auth". 

I just added "zfcampus/zf-content-negotiation" : "1.0.7" (from may, 5) as a temporary solution.

Thanks and keep the good work.

**Comment by weierophinney** [comment]
This is not an issue of zf-content-negotiation; #108 is the correct report. Essentially, the zf-oauth2 configuration is incorrect. I'll get it fixed.
