### ISSUE TITLE
1.0.8 break

### ISSUE THREAD

**Issue by kris-sum** [zfcampus/zf-content-negotiation#47]
upgrading from 1.0.7 to 1.0.8 I get an error

> Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "ZF\OAuth2\Controller\Auth" does not have a matching "setZF\OAuth2\Controller\Auth" ("setZF\OAuth2\Controller\Auth") setter method which must be defined' in /vagrant/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930

Trace:

Function | Location
------------ | ---------------
ZF\ContentNegotiation\Factory\ContentNegotiationOptionsFactory->createService( ) | ../ServiceManager.php:923
Zend\Stdlib\AbstractOptions->__construct( )	| ../ContentNegotiationOptionsFactory.php:31
Zend\Stdlib\AbstractOptions->setFromArray( ) | ../AbstractOptions.php:32
Zend\Stdlib\AbstractOptions->__set( ) | ../AbstractOptions.php:62

**Comment by weierophinney** [comment]
Please do the following:

```console
$ composer update zfcampus/zf-oauth2
```

and make sure you get at least version 1.2.0 of zf-oauth2 installed.

Version 1.2.0 of zf-oauth2 fixes its content-negotiation rules; the previous versions were incorrect, and, in fact, ignored because they used invalid keys. New changes on zf-content-negotiation highlight the problem.

**Comment by weierophinney** [comment]
I've also tagged 1.1.3 that contains the same fix from zfcampus/zf-oauth2#108, allowing you to keep a 1.1 series zf-oauth2 version if desired.

**Comment by kris-sum** [comment]
Many thanks, all fixed here. Appreciate the speedy response!
