### ISSUE TITLE
Empty Accept/Missing headers are not accepted

### ISSUE THREAD

**Issue by erik-maas** [zfcampus/zf-content-negotiation#62]
As it stands,
Zf-content-negotiation does not accept a request missing a accept header.

This could be solved with ease by defaulting to: Accept: */*
Replacing the first lines of validateMediaType to: 
`protected function validateMediaType($match, HttpHeaders $headers)
    {
        if (!$headers->has('accept')) {
            $headers->addHeaderLine('accept', '*/*');
        }`

This would fix the issue that quite some services on the web do not supply the header (rendering this library useless).

**Comment by TomHAnderson** [comment]
:-1: Apigility is more correct than these services.  The bug is on the their implementation, not Apigility.

**Comment by TomHAnderson** [comment]
@erik-maas please submit your code revision as a pull request instead of an inline comment.

**Comment by weierophinney** [comment]
Fixed with #58.
