### ISSUE TITLE
Release 1.1.2 disallow PHP 7

### ISSUE THREAD

**Issue by webimpress** [zfcampus/zf-content-negotiation#69]
Hi,
why with release [1.1.2](https://github.com/zfcampus/zf-content-negotiation/compare/1.1.1...1.1.2) in `composer.json` php requirement was changed from `>=5.5` to `^5.5`?
Now is not possible to use it on PHP7.

https://github.com/zfcampus/zf-content-negotiation/commit/9d0bcea51cfcaffad059ed4fa92dae64f1283702#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R29

**Comment by weierophinney** [comment]
@webimpress Because we hadn't tested with php 7 to ensure it worked correctly.

The upcoming v1.2 is tested correctly against it, and will contain the support.
