### ISSUE TITLE
Cyclic aliases

### ISSUE THREAD

**Issue by autowp** [zfcampus/zf-content-negotiation#72]
Uncaught exception 'Zend\ServiceManager\Exception\CyclicAliasException' with message 'Cycles were detected within the provided aliases: 
[
  "filerenameupload" => "Zend\Filter\File\RenameUpload" => "filerenameupload" "fileRenameUpload" => "Zend\Filter\File\RenameUpload" => "filerenameupload" => "fileRenameUpload" "FileRenameUpload" => "Zend\Filter\File\RenameUpload" => "filerenameupload" => "FileRenameUpload" ] 

https://github.com/zfcampus/zf-content-negotiation/blob/master/config/module.config.php#L19
https://github.com/zendframework/zend-filter/blob/master/src/FilterPluginManager.php#L101

**Comment by MichaelGooden** [comment]
Looks like you have worked this out, patches welcome!
