### ISSUE TITLE
Failing unit test on Mac

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-content-negotiation#82]
In `\ZFTest\ContentNegotiation\ContentTypeListenerTest`, there is a test to show that a file is removed from the tmp directory after upload is done - `testOnFinishWillRemoveAnyUploadFilesUploadedByTheListener`. 

The test is failing because the listener is doing some sanity checks that don't work on the mac. In `\ZF\ContentNegotiation\ContentTypeListener`, in the `onFinish` method (line 132), there's a check to ensure the directory the temporary file is in matches the one expected from the listener. On the mac, during one particular run, the MultipartContentParser::getUploadTempDir returned a value of `/var/folders/h7/m7pxgyxj4c77rcs9mm4b_bvc0000gp/T`. However, when writing to that directory, the file path included or specified ends up being `/private/var/folders/h7/m7pxgyxj4c77rcs9mm4b_bvc0000gp/T/zfcp60K8E`. Note the addition of `/private`. It's the same place, but the check will fail and the files will not be removed.

I'm happy to submit a patch for it, but I'd like to know what way you'd prefer to solve it.

**Comment by weierophinney** [comment]
Fixed with #94.
