### ISSUE TITLE
Since 1.3.1 : Notice: Uninitialized string offset: 0 in ../ContentTypeListener.php on line 105

### ISSUE THREAD

**Issue by NicolasCayet** [zfcampus/zf-content-negotiation#96]
Hello,

After trying to use the last 1.3.1 version early released, i issued with this error notice : 
Notice: Uninitialized string offset: 0 in ../vendor/zfcampus/zf-content-negotiation/src/ContentTypeListener.php on line 105

This notice appears on PATCH / PUT / DELETE request, whenever you did not pass any HTTP body − which is possible following standards.

As we can see within the code, trying to auto-detect JSON format in body when no Content-Type is provided is fine, but it must first detect if any body has been provided...

https://github.com/zfcampus/zf-content-negotiation/blob/4bf815bf428cdd4d6e6a658c9898d82998a4c124/src/ContentTypeListener.php#L105

**Comment by weierophinney** [comment]
Fixed with version 1.3.2.
